/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package goitpackage;

public class App {


    public static void main(String[] args) {
     int var;
      var=  SumCalculator.sum(3);
    }
}
